version: "3"
services:
  test:
    build: .
    ports:
      - "3100"
    container_name: gfw-geostore-api-test
    environment:
      NODE_ENV: test
      NODE_PATH: app/src
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      STAMPERY_TOKEN: token
      MONGO_PORT_27017_TCP_ADDR: mongo
    command: test
    depends_on:
      - mongo
  mongo:
    image: mongo
    command: --smallfiles
    ports:
      - "27017"
    restart: always
