version: "3"
services:
  develop:
    build: .
    ports:
      - "35731:35729"
    container_name: gfw-geostore-api-develop
    env_file:
      - dev.env
    environment:
      NODE_ENV: dev
      NODE_PATH: app/src
      CARTODB_USER: wri-01
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      MONGO_PORT_27017_TCP_ADDR: mongo
    command: develop
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/gfw-geostore-api/app
  mongo:
    image: mongo:3.4
    container_name: gfw-geostore-mon
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - $HOME/docker/data/gfw-geostore-api:/data/db
    restart: always
